// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc.proto

#include "rpc.pb.h"
#include "rpc.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* RpcTestService_method_names[] = {
  "/RpcTestService/Search",
};

std::unique_ptr< RpcTestService::Stub> RpcTestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RpcTestService::Stub> stub(new RpcTestService::Stub(channel));
  return stub;
}

RpcTestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Search_(RpcTestService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RpcTestService::Stub::Search(::grpc::ClientContext* context, const ::RpcTestServiceRequest& request, ::RpcTestServiceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Search_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::RpcTestServiceResponse>* RpcTestService::Stub::AsyncSearchRaw(::grpc::ClientContext* context, const ::RpcTestServiceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::RpcTestServiceResponse>::Create(channel_.get(), cq, rpcmethod_Search_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::RpcTestServiceResponse>* RpcTestService::Stub::PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::RpcTestServiceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::RpcTestServiceResponse>::Create(channel_.get(), cq, rpcmethod_Search_, context, request, false);
}

RpcTestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RpcTestService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RpcTestService::Service, ::RpcTestServiceRequest, ::RpcTestServiceResponse>(
          std::mem_fn(&RpcTestService::Service::Search), this)));
}

RpcTestService::Service::~Service() {
}

::grpc::Status RpcTestService::Service::Search(::grpc::ServerContext* context, const ::RpcTestServiceRequest* request, ::RpcTestServiceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


